const { GoogleGenAI } = require("@google/genai");
const {z}= require("zod")
const {zodToJsonSchema}=require("zod-to-json-schema")
const puppeteer=require("puppeteer")

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});


const interviewReportSchema=z.object({
  matchScore:z.number().describe("The percentage match between the candidate's profile and the job describe"),
  technicalQuestions:z.array(z.object({
    question:z.string().describe("The technical question that can be asked in the interview"),
    intension:z.string().describe("The intention behind asking this question"),
    answer:z.string().describe("How to answer this question,what points to cover,what structure to follow etc.")
  })).describe("Technical questions that can be asked in the interview"),
  behavioralQQuestions:z.array(z.object({
    question:z.string().describe("The behavioral question that can be asked in the interview"),
    intension:z.string().describe("The intention behind asking this question"),
    answer:z.string().describe("How to answer this question,what points to cover,what structure to follow etc.")
  })).describe("Behavioral questions that can be asked in the interview"),
  skillsGap:z.array(z.object({
    skill:z.string().describe("The skill that the candidate is lacking"),
    severity:z.enum(["low","medium","high"]).describe("The severity of the skill gap")
  })).describe("Skills gaps identified in the candidate"),
  preparationPlan:z.array(z.object({
    day:z.number().describe("The day number in the preparation plan"),
    focus:z.string().describe("The main focus of the day"),
    task:z.array(z.string()).describe("The tasks to be done on that day")
  })).describe("A day-wise preparation plan for the candidate"),
  title:z.string().describe("The title of the job for which the interview  report is generated"),
})

async function generateInterviewReport({resume,selfDescription,jobDescription}){

  const prompt=`Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.`

  const response=await ai.models.generateContent({
    model:"gemini-2.5-flash",
    contents:prompt,
    config:{
      responseMimeType:"application/json",
      responseSchema:zodToJsonSchema(interviewReportSchema)
    }
  })

  return JSON.parse(response.text)

}


async function generatePdfFromHtml(htmlContent){
  const browser=await puppeteer.launch()
  const page=await browser.newPage();
  await page.setContent(htmlContent,{waitUntil:"networkidle0"})

  const pdfBuffer=await page.pdf({
    format:"A4",
  })
  
  await browser.close()
  return pdfBuffer
}

//ai generates the HTML and Pupeteer turns html to PDF
async function generateResumePdf({resume,selfDescription,jobDescription}){
  const resumepdfSchema=z.object({
    html=z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer.")
  })

  const prompt=`Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF
                        `

  const response=await ai.models.generateContent({
    model:"gemini-3-flash-preview",
    contents:prompt,
    config:{
      responseMimeType:"application/json",
      responseSchema:zodToJsonSchema(resumepdfSchema)
    }
  })

  const jsonContent=JSON.parse(response.text)
  return jsonContent

}



module.exports = {
  generateInterviewReport,
  generateResumePdf
};

